# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-22 22:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0025_auto_20181022_1737'),
        ('sales', '0016_auto_20181019_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrderSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Reporte de entrega',
                'proxy': True,
                'verbose_name_plural': 'Reportes de entregas',
                'indexes': [],
            },
            bases=('sales.deliveryorder',),
        ),
        migrations.CreateModel(
            name='OrderSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Reporte de venta',
                'proxy': True,
                'verbose_name_plural': 'Reportes de ventas',
                'indexes': [],
            },
            bases=('sales.order',),
        ),
        migrations.CreateModel(
            name='ProductSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Reporte de producto',
                'proxy': True,
                'verbose_name_plural': 'Reportes de productos',
                'indexes': [],
            },
            bases=('stock.product',),
        ),
        migrations.CreateModel(
            name='RatingSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Reporte de calificacion',
                'proxy': True,
                'verbose_name_plural': 'Reportes de calificaciones',
                'indexes': [],
            },
            bases=('sales.rating',),
        ),
    ]
