# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Marca'},
        ),
    ]
