# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20170802_0739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storeparameter',
            options={'verbose_name': 'Par\xe1metro de tienda', 'verbose_name_plural': 'Par\xe1metros de tiendas'},
        ),
    ]
