# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20170802_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
