# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_inventory_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
