# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-25 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_auto_20170819_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stock/products/images/'),
        ),
    ]
