# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-07 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_auto_20170907_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storecontact',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_contacts', to='stock.Store'),
        ),
        migrations.AlterField(
            model_name='storehour',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_hours', to='stock.Store'),
        ),
    ]
