# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-28 05:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_auto_20170927_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_stores', to='manager.City'),
        ),
    ]
