# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-29 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0016_auto_20170928_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeparameter',
            name='delivery_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
