# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-01 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0017_auto_20170929_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='web_cover',
            field=models.ImageField(blank=True, null=True, upload_to='stock/stores/web_covers/'),
        ),
    ]
