# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-02 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0018_store_web_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='stock/products/images/'),
        ),
    ]
