# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-06 00:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0019_auto_20171001_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_categories', to='stock.Category'),
        ),
    ]
