# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-07 16:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0025_auto_20181022_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2018, 11, 7, 16, 20, 46, 740824, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
