# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-01 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0025_auto_20181022_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stock/products/images/'),
        ),
    ]
