# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-13 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0026_product_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='logo.png', upload_to='stock/products/images/'),
        ),
    ]
