# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-08 21:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0026_product_date_added'),
        ('stock', '0026_auto_20181101_1058'),
    ]

    operations = [
    ]
