# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-06-07 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_bank'),
        ('stock', '0032_auto_20190302_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.Bank', verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='store',
            name='bank_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numero de cuenta'),
        ),
        migrations.AddField(
            model_name='store',
            name='bank_type',
            field=models.CharField(blank=True, choices=[('AH', 'Ahorros'), ('CO', 'Corriente')], max_length=2, null=True, verbose_name='Tipo de cuenta'),
        ),
    ]
