# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20170802_0547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Ciudad', 'verbose_name_plural': 'Ciudades'},
        ),
        migrations.AlterModelOptions(
            name='faqcategory',
            options={'verbose_name': 'Categor\xeda de FAQ', 'verbose_name_plural': 'Categor\xedas de FAQ'},
        ),
        migrations.AlterModelOptions(
            name='faqitem',
            options={'verbose_name': 'Item de FAQ', 'verbose_name_plural': 'Items de FAQ'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name': 'Region', 'verbose_name_plural': 'Regiones'},
        ),
    ]
