# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 00:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_apikey'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apikey',
            options={'ordering': ['-created'], 'verbose_name': 'Llave de API', 'verbose_name_plural': 'Llaves de API'},
        ),
    ]
