# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-28 05:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_cities', to='manager.State'),
        ),
    ]
