# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-06-07 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_bank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'verbose_name': 'Banco'},
        ),
    ]
