# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-19 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20170906_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sales.Order'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sales.Order'),
        ),
    ]
