# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-19 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_token'),
        ('sales', '0003_auto_20170919_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Address'),
        ),
    ]
