# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-19 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_deliveryorder_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='extra_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='payment_method',
            field=models.CharField(choices=[('CS', 'Cash'), ('PS', 'POS')], max_length=2),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='status',
            field=models.CharField(choices=[('RN', 'Running'), ('DV', 'Delivered'), ('CA', 'Cancelled')], max_length=2),
        ),
    ]
