# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-21 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20170919_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='status',
            field=models.CharField(choices=[('RN', 'Running'), ('DV', 'Delivered'), ('CA', 'Cancelled')], default='RN', max_length=2),
        ),
    ]
