# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-29 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_auto_20170929_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PE', 'Pendiente'), ('AC', 'Aceptada'), ('CA', 'Cancelada'), ('DE', 'Entregada')], default='PE', max_length=2),
        ),
    ]
