# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-04 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_auto_20171003_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_order', to='sales.Order'),
        ),
    ]
