# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-05 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_auto_20171004_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='payment_method',
            field=models.CharField(choices=[('CS', 'Efectivo'), ('PS', 'Dat\xe1fono')], max_length=2),
        ),
    ]
