# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-06 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_order_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PE', 'Pendiente'), ('AC', 'Recibida'), ('SH', 'Enviada'), ('CA', 'Cancelada'), ('DE', 'Entregada')], default='PE', max_length=2),
        ),
    ]
