# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-08 14:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_auto_20181019_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2018, 11, 8, 14, 46, 33, 220965, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
