# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-29 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_auto_20181108_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Address', verbose_name='Direcci\xf3n'),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='extra_details',
            field=models.TextField(blank=True, null=True, verbose_name='Datos extra'),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor pagado'),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='payment_method',
            field=models.CharField(choices=[('CS', 'Efectivo'), ('PS', 'Dat\xe1fono')], max_length=2, verbose_name='M\xe9todo de pago'),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='status',
            field=models.CharField(choices=[('RN', 'En ejecuci\xf3n'), ('DV', 'Entregado'), ('CA', 'Cancelado')], default='RN', max_length=2, verbose_name='Estado'),
        ),
    ]
