# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-06-07 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_auto_20190518_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='payment_method',
            field=models.CharField(choices=[('CS', 'Efectivo'), ('PS', 'Dat\xe1fono'), ('BA', 'Consignaci\xf3n o transferencia bancaria')], max_length=2, verbose_name='M\xe9todo de pago'),
        ),
    ]
