# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-30 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='directions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
