# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-04 20:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170929_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_addresses', to=settings.AUTH_USER_MODEL),
        ),
    ]
