# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-04 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20171005_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('CL', 'Cliente'), ('MG', 'Administrador Tienda')], default='CL', max_length=2, verbose_name='Tipo de Usuario'),
        ),
    ]
