# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-11 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
